quarkus:
  application:
    name: Gestion de Colaboradores
    version: 1.0-SNAPSHOT

  # HTTP
  http:
    port: ${PORT:8080}
    host: 0.0.0.0
    root-path: /kkom

  # Base de datos - PostgreSQL (Render Cloud)
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}?sslmode=require

  # Hibernate ORM
  hibernate-orm:
    database:
      generation: update # Actualiza el esquema de la base de datos automáticamente
    log:
      sql: true

  # Configuracion de Logs
  log:
    level: INFO
    console:
      enabled: true
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      

    file:
      enabled: true
      path: logs/gclientes.log
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n"
      rotation:
        max-file-size: 5M
        max-backup-index: 5
        file-suffix: yyyy-MM-dd

  swagger-ui:
    enabled: true
    always-include: true
    path: "/swagger-ui"
    
    

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: "Comedor Comunitario"
          version: "1.1.0"

"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
      username: sa
      password: ""
    hibernate-orm:
      schema-management:
        strategy: drop-and-create
